### ISSUE TITLE
Older python versions than 3.10

### ISSUE THREAD

**Issue by Timtam** [synthizer/synthizer-python#10]
Is there a specific reason for the build drop on older versions than 3.10 on Windows? Most of thoise versions still get supported by Python, and having wheels available for the newest versions only complicates things alot as soon as you're trying to have synthizer as a default dependency (like within audio game frameworks and such). I have to stick with synthizer 0.12 right now, since that's the last version that also offers builds for older python versions and I don't want people who just want to write a quick python program on Python 3.9 or 3.8 or something (because they are used to it or something) to go through all the manual synthizer building steps, nor will I force them to upgrade as long as the python version is officially supported.

**Comment by ahicks92** [comment]
Back when this was more active and entirely me as the maintainer Saturdays turned into push a commit and wait to see if it broke on platforms that aren't mine, push a release and check back in on it every 10-15 minutes, etc etc...was taking longer than actually coding the damned thing by an order of magnitude.

I disagree with your reasoning here, but it doesn't hurt to add back 3.9, and given that wx somehow hasn't put up wheels that does make some sense as a thing worth doing.  This is reasonably straightforward save that monitoring the build will take forever, so if you want it sooner than Saturday you'll want to send a PR.

But here's the thing.  Python 3.8 was 2019.  VS 2017 was either late 2017 or early 2018.  You don't have to install cmake or ninja or any of that.  I think it should be reasonable to expect users to upgrade their tools every 3 years, and this issue in essence boils down to you saying that that's not a reasonable expectation.  For now I'm happy to do this, but if this somehow turns into me as the primary contributor again, we'll have to revisit this.  My time is more valuable to me than supporting effectively ancient compilers and python versions.

**Comment by Timtam** [comment]
> Back when this was more active and entirely me as the maintainer Saturdays turned into push a commit and wait to see if it broke on platforms that aren't mine, push a release and check back in on it every 10-15 minutes, etc etc...was taking longer than actually coding the damned thing by an order of magnitude.

Understandable. I usually just continue coding and will get informed via mail if my build broke at some point, and my projects usually don't build in under an hour (Bass4Py cython build takes about 1h20 sometimes for 1 build, and i'm monitoring projects which take even longer to build a single docker container and it still does work for them, with much more devs than this project has).

> But here's the thing. Python 3.8 was 2019. VS 2017 was either late 2017 or early 2018. You don't have to install cmake or ninja or any of that. I think it should be reasonable to expect users to upgrade their tools every 3 years, and this issue in essence boils down to you saying that that's not a reasonable expectation. 

A little bit narrow-minded IMO. I for example do have VS2017 enterprise and am using it still because it still receives support and updates, and I don't have an Enterprise license for newer VS versions, nor do I need newer features right now. I don't feel like installing every single VS community version because every projects requires a different one or someone asks me to do so, everything else is still working. And there might be other valid reasons that I can't think of right now that are totally fine and don't fall into the "well I always update to the latest version as soon as possible" rule of thumb. Developers trying to use synthizer as a tool for their business might be limited on what they are actually allowed to install, they might not even have the option to install a newer version than 2017, 'cause that would require the company to buy a new license which is kinda expensive (that was the situation at my previous employer for quite a while).

And 2017 is just here for demonstration purposes, you might be switching over to the latest compiler again in a year or so, dropping support for older compilers in the process while others can't do that yet, for whatever reason.

> For now I'm happy to do this, but if this somehow turns into me as the primary contributor again, we'll have to revisit this. My time is more valuable to me than supporting effectively ancient compilers and python versions.

Well, right now your userbase is quite small. I think your time might become more valuable as soon as alot of people come here to ask you the same question over and over, "why doesn't this build here", "I get that C error, what can I do?" etc etc. You got build configuration for previous python versions here already, adding them in, except waiting for the builds to finish, just takes a few minutes and will probably save you the support time in the long run, at least thats how I see things. You either lose time waiting for builds, or answering support requests. You either change your workflow to not wait for builds, because you can always stash inbetween your current work to fix an error with the latest build, or you don't answer support requests at all and people will just wander off not using your product because of that. Just discussing the possibilities of course.

I just wanted to kick off the discussion again. For now i'm using synthizer 0.12 because i'm developing a lib which supports Python 3.7 onward, and as long as I do that, i'll have to stick with the latest Synthizer version that either supports wheels for those versions or builds out of the box without having to mess around with specific dependencies or prerequisites, or i'll have to make synthizer an optional addition and replace the default component with something more flexible. Its just clear that we're prioritizing LTS support differently, and our workflow probably kinda differs as well ;).

**Comment by ahicks92** [comment]
To be clear before I continue I already said yes, send me a PR or wait a week.  Not sure we can go back as far as 3.7 anymore/at all though, I'm not sure I even supported that originally.  If I did then probably it still works.  The following is sort of the "if this was actively maintained" stance but as long as this is in maintenance mode I'm not sure I really care about these points, so if it's just putting some values back in the lists shrug.

This has been 2019 from day one. I haven't bumped that, don't intend to, and also kinda can't.  Unfortunately the C++ side of things moves somewhat fast these days; depending on what comes down the pipeline and what compilers end up supporting it, I could see an upgrade happening in 2 years from now maybe.

Context switching is expensive.  It's hard to work on other things when 15-30 minutes from now or however long it ends up being is going to require me to come back and hit more buttons or fix problems.  Synthizer is 3 libraries and I also have Ammo.

If this gets more popular then there are presumably more contributors, doing things like LTS and whatnot becomes less of my specific problem.

GitHub Actions has parallelism limits.  Appveyor has even worse ones and also charges a *ton* of money to fix them.  If this did become popular and we did have half-hour CI jobs, then we run up against the build queue.  At the end of the day scaling CI out costs money beyond a certain point.

We aren't discussing enterprise environments, or weren't originally.  If you're in or know someone in an enterprise environment that has those restrictions who also wants to use Synthizer specifically in Python then I'm thrilled to discuss supporting that, and will quote an hourly rate for them.

Saying "well this old version is supported" isn't actually really saying much because most of those old versions are supported in the sense of security patching and really critical bugfixes.  I'm not the only OSS dev who doesn't care about extremely long LTS periods.  When your engine gets more advanced you're going to begin running into this with other dependencies.  Everyone wants/expects you to upgrade, they're just providing a path for those who can't.  If the stance is "everything still officially supported should be supported" you end up in really weird places in general, and as long as I'm not being paid for my time most of my projects aren't going to take that stance.

If you don't want full VS installs you can install the C++ build tools only.  Things like Anaconda can manage this for you automatically.

Or put another way: when this is successful/actually gets enough people then your points become more compelling, till then I don't agree with the stance.

**Comment by ahicks92** [comment]
Ok, so good news. Somewhere along the way GitHub raised the concurrency limit to 20 jobs.  It used to be much lower, but it does mean this can scale out more than when I originally took them off.  I'm trying to get this in real quick this evening but we'll see--if I did it right the first time it's done, if not I likely will have to push out.

**Comment by ahicks92** [comment]
Done.
