### ISSUE TITLE
random errors while trying to install python weels

### ISSUE THREAD

**Issue by falisca** [synthizer/synthizer-python#9]
Hi, I'm encountering strange and random errors installing the Python wheels, version 0.12.1
Seems that the Cython compilation can't find some header files, different ones on every run.
The problem occured in a new virtual environment, on Windows. I'm thinking it could be some configuration problem on my machine but can't tell what...
"synthizer-vendored\include\synthizer/audio_output.hpp(3): fatal error C1083: can't open include file: 'atomic': No such file or directory"
or on a previous run it gived:
"synthizer-vendored\include\synthizer/biquad.hpp(5): fatal error C1083: can't open include file: 'memory': No such file or directory"

I attach pip log for reference.

After the installation aborts pip installs the previous version, that installs fine but give me errors at instantiation time. That is matter for an other issue.
Please note that previously I succesfully used Synthizer in some projects, don't remember what version.

Any ideas?
Cheers.
[pip3.log](https://github.com/synthizer/synthizer/files/7854003/pip3.log)

**Comment by falisca** [comment]
Thanks, that was a stupid problem caused by miself, updating to Python 3.10.1 worked perfectly.
I thinked wrongly that Python 3.8 was enough, also I didn't know that the python specific repo exists, sorry for the confusion.
Cheers.

**Comment by ahicks92** [comment]
Python 3.8 is enough, if you are set up to build Python C extensions.  Nothing wrong with the upgrade, but fwiw you'll have to figure this out for something else eventually.

The issue is that running CI against all Python versions Synthizer can support on all platforms was becoming too expensive and requiring a half hour wait to know if CI is going to succeed, so we still check that the older versions work but we don't publish binaries.
